/// USB HID mouse driver for MerlionOS.
/// Supports USB mice via HID boot protocol with buttons,
/// movement, and scroll wheel.
///
/// Parses 3-byte (standard) and 4-byte (scroll) HID boot-protocol mouse
/// reports.  Tracks absolute cursor position from relative deltas, supports
/// integer-math acceleration, double-click detection, and falls back to
/// PS/2 mouse packets (IRQ12) when no USB mouse is present.

use alloc::string::String;
use alloc::format;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicI32, Ordering};
use spin::Mutex;

// ---------------------------------------------------------------------------
// HID boot-protocol mouse report layout
// ---------------------------------------------------------------------------

/// Boot-protocol report: byte 0 = buttons, byte 1 = X delta, byte 2 = Y delta.
/// Optional byte 3 = wheel delta.
const HID_BOOT_REPORT_MIN: usize = 3;
const HID_BOOT_REPORT_MAX: usize = 4;

// Button bits in report byte 0
const BTN_LEFT: u8   = 1 << 0;
const BTN_RIGHT: u8  = 1 << 1;
const BTN_MIDDLE: u8 = 1 << 2;
const BTN_4: u8      = 1 << 3;
const BTN_5: u8      = 1 << 4;

// ---------------------------------------------------------------------------
// PS/2 fallback constants
// ---------------------------------------------------------------------------

const PS2_FLAG_LEFT: u8       = 0x01;
const PS2_FLAG_RIGHT: u8      = 0x02;
const PS2_FLAG_MIDDLE: u8     = 0x04;
const PS2_FLAG_X_SIGN: u8     = 0x10;
const PS2_FLAG_Y_SIGN: u8     = 0x20;
const PS2_FLAG_X_OVERFLOW: u8 = 0x40;
const PS2_FLAG_Y_OVERFLOW: u8 = 0x80;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// Mouse button identifiers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    Button4,
    Button5,
}

/// Events generated by the mouse driver.
#[derive(Debug, Clone)]
pub enum MouseEvent {
    Move { x: i32, y: i32 },
    ButtonDown(MouseButton),
    ButtonUp(MouseButton),
    Scroll(i32),
}

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

struct UsbMouseState {
    /// Absolute cursor X.
    x: i32,
    /// Absolute cursor Y.
    y: i32,
    /// Screen width bound.
    width: i32,
    /// Screen height bound.
    height: i32,
    /// Button state: left, right, middle, button4, button5.
    buttons: [bool; 5],
    /// Acceleration numerator (speed_factor / 10).  Default 10 = 1x.
    accel_num: i32,
    /// Tick of last left-click for double-click detection.
    last_click_tick: u64,
    /// Whether the last click was the first of a potential double-click.
    awaiting_double: bool,
    /// Total packets processed.
    packets: u64,
    /// Total move events.
    moves: u64,
    /// Total button events.
    button_events: u64,
    /// Total scroll events.
    scroll_events: u64,
    /// Double-clicks detected.
    double_clicks: u64,
    /// Pending event queue (ring buffer).
    event_buf: [Option<MouseEventCompact>; EVENT_BUF_SIZE],
    event_head: usize,
    event_tail: usize,
}

/// Compact representation for the internal ring buffer.
#[derive(Debug, Clone, Copy)]
enum MouseEventCompact {
    Move { x: i32, y: i32 },
    ButtonDown(u8),
    ButtonUp(u8),
    Scroll(i32),
}

const EVENT_BUF_SIZE: usize = 64;

/// Double-click threshold in timer ticks (roughly 400ms at 100Hz PIT).
const DOUBLE_CLICK_TICKS: u64 = 40;

static STATE: Mutex<UsbMouseState> = Mutex::new(UsbMouseState {
    x: 320,
    y: 240,
    width: 640,
    height: 480,
    buttons: [false; 5],
    accel_num: 10,
    last_click_tick: 0,
    awaiting_double: false,
    packets: 0,
    moves: 0,
    button_events: 0,
    scroll_events: 0,
    double_clicks: 0,
    event_buf: [None; EVENT_BUF_SIZE],
    event_head: 0,
    event_tail: 0,
});

static INITIALIZED: AtomicBool = AtomicBool::new(false);
static USB_PRESENT: AtomicBool = AtomicBool::new(false);

// PS/2 fallback packet assembly
static PS2_PACKET_IDX: AtomicU32 = AtomicU32::new(0);
static PS2_PACKET_BUF: Mutex<[u8; 3]> = Mutex::new([0u8; 3]);

// Cumulative delta accumulators for poll-based reporting
static DELTA_X: AtomicI32 = AtomicI32::new(0);
static DELTA_Y: AtomicI32 = AtomicI32::new(0);

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

impl UsbMouseState {
    fn push_event(&mut self, ev: MouseEventCompact) {
        let next = (self.event_head + 1) % EVENT_BUF_SIZE;
        if next != self.event_tail {
            self.event_buf[self.event_head] = Some(ev);
            self.event_head = next;
        }
        // If full, drop oldest events silently.
    }

    fn pop_event(&mut self) -> Option<MouseEventCompact> {
        if self.event_tail == self.event_head {
            return None;
        }
        let ev = self.event_buf[self.event_tail].take();
        self.event_tail = (self.event_tail + 1) % EVENT_BUF_SIZE;
        ev
    }

    /// Apply acceleration to a raw delta value.
    fn accelerate(&self, delta: i32) -> i32 {
        // Integer acceleration: delta * accel_num / 10
        // For small movements (abs <= 3), no acceleration for precision.
        if delta.abs() <= 3 {
            delta
        } else {
            (delta * self.accel_num) / 10
        }
    }

    fn clamp_position(&mut self) {
        if self.x < 0 { self.x = 0; }
        if self.y < 0 { self.y = 0; }
        if self.x >= self.width { self.x = self.width - 1; }
        if self.y >= self.height { self.y = self.height - 1; }
    }

    fn process_buttons(&mut self, new_buttons: [bool; 5], tick: u64) {
        const BUTTON_MAP: [MouseButton; 5] = [
            MouseButton::Left,
            MouseButton::Right,
            MouseButton::Middle,
            MouseButton::Button4,
            MouseButton::Button5,
        ];
        for i in 0..5 {
            if new_buttons[i] != self.buttons[i] {
                self.button_events += 1;
                if new_buttons[i] {
                    self.push_event(MouseEventCompact::ButtonDown(i as u8));
                    // Double-click detection on left button
                    if i == 0 {
                        let _ = BUTTON_MAP[i]; // suppress unused warning
                        if self.awaiting_double && tick.wrapping_sub(self.last_click_tick) < DOUBLE_CLICK_TICKS {
                            self.double_clicks += 1;
                            self.awaiting_double = false;
                        } else {
                            self.awaiting_double = true;
                            self.last_click_tick = tick;
                        }
                    }
                } else {
                    self.push_event(MouseEventCompact::ButtonUp(i as u8));
                }
                self.buttons[i] = new_buttons[i];
            }
        }
    }
}

fn compact_to_event(compact: MouseEventCompact) -> MouseEvent {
    const BUTTON_MAP: [MouseButton; 5] = [
        MouseButton::Left,
        MouseButton::Right,
        MouseButton::Middle,
        MouseButton::Button4,
        MouseButton::Button5,
    ];
    match compact {
        MouseEventCompact::Move { x, y } => MouseEvent::Move { x, y },
        MouseEventCompact::ButtonDown(idx) => {
            MouseEvent::ButtonDown(BUTTON_MAP[idx as usize % 5])
        }
        MouseEventCompact::ButtonUp(idx) => {
            MouseEvent::ButtonUp(BUTTON_MAP[idx as usize % 5])
        }
        MouseEventCompact::Scroll(delta) => MouseEvent::Scroll(delta),
    }
}

// ---------------------------------------------------------------------------
// USB HID report processing
// ---------------------------------------------------------------------------

/// Process a USB HID boot-protocol mouse report.
///
/// `report` must be 3 or 4 bytes long (buttons, dx, dy, [wheel]).
pub fn process_hid_report(report: &[u8]) {
    if report.len() < HID_BOOT_REPORT_MIN || report.len() > HID_BOOT_REPORT_MAX {
        return;
    }

    let buttons_byte = report[0];
    let raw_dx = report[1] as i8 as i32;
    let raw_dy = report[2] as i8 as i32;
    let raw_wheel = if report.len() >= 4 { report[3] as i8 as i32 } else { 0 };

    let new_buttons = [
        buttons_byte & BTN_LEFT != 0,
        buttons_byte & BTN_RIGHT != 0,
        buttons_byte & BTN_MIDDLE != 0,
        buttons_byte & BTN_4 != 0,
        buttons_byte & BTN_5 != 0,
    ];

    USB_PRESENT.store(true, Ordering::Relaxed);
    let tick = crate::timer::ticks();
    let mut s = STATE.lock();
    s.packets += 1;

    // Apply acceleration
    let dx = s.accelerate(raw_dx);
    let dy = s.accelerate(raw_dy);

    // Update absolute position
    if dx != 0 || dy != 0 {
        s.x += dx;
        s.y += dy;
        s.clamp_position();
        s.moves += 1;
        let cx = s.x;
        let cy = s.y;
        s.push_event(MouseEventCompact::Move { x: cx, y: cy });
        DELTA_X.fetch_add(dx, Ordering::Relaxed);
        DELTA_Y.fetch_add(dy, Ordering::Relaxed);
    }

    // Scroll wheel
    if raw_wheel != 0 {
        s.scroll_events += 1;
        s.push_event(MouseEventCompact::Scroll(raw_wheel));
    }

    // Buttons
    s.process_buttons(new_buttons, tick);
}

// ---------------------------------------------------------------------------
// PS/2 mouse fallback (IRQ12)
// ---------------------------------------------------------------------------

/// Feed one byte from IRQ12 into the PS/2 packet state machine.
/// Falls back to PS/2 protocol when no USB mouse is detected.
pub fn handle_ps2_irq(byte: u8) {
    if USB_PRESENT.load(Ordering::Relaxed) {
        return; // USB mouse is active, ignore PS/2
    }

    let idx = PS2_PACKET_IDX.load(Ordering::Relaxed);
    match idx {
        0 => {
            if byte & 0x08 == 0 {
                return; // Not a valid flags byte, stay at index 0
            }
            PS2_PACKET_BUF.lock()[0] = byte;
            PS2_PACKET_IDX.store(1, Ordering::Relaxed);
        }
        1 => {
            PS2_PACKET_BUF.lock()[1] = byte;
            PS2_PACKET_IDX.store(2, Ordering::Relaxed);
        }
        2 => {
            let buf = {
                let locked = PS2_PACKET_BUF.lock();
                [locked[0], locked[1], byte]
            };
            PS2_PACKET_IDX.store(0, Ordering::Relaxed);

            let flags = buf[0];
            let raw_dx_byte = buf[1];
            let raw_dy_byte = buf[2];

            // Discard overflow packets
            if flags & (PS2_FLAG_X_OVERFLOW | PS2_FLAG_Y_OVERFLOW) != 0 {
                return;
            }

            // Sign-extend 9-bit deltas
            let dx: i32 = if flags & PS2_FLAG_X_SIGN != 0 {
                raw_dx_byte as i32 - 256
            } else {
                raw_dx_byte as i32
            };
            let dy: i32 = if flags & PS2_FLAG_Y_SIGN != 0 {
                -(raw_dy_byte as i32 - 256)
            } else {
                -(raw_dy_byte as i32)
            };

            let new_buttons = [
                flags & PS2_FLAG_LEFT != 0,
                flags & PS2_FLAG_RIGHT != 0,
                flags & PS2_FLAG_MIDDLE != 0,
                false,
                false,
            ];

            // Build a synthetic 3-byte HID report and process it
            let tick = crate::timer::ticks();
            let mut s = STATE.lock();
            s.packets += 1;

            let adx = s.accelerate(dx);
            let ady = s.accelerate(dy);

            if adx != 0 || ady != 0 {
                s.x += adx;
                s.y += ady;
                s.clamp_position();
                s.moves += 1;
                let cx = s.x;
                let cy = s.y;
                s.push_event(MouseEventCompact::Move { x: cx, y: cy });
                DELTA_X.fetch_add(adx, Ordering::Relaxed);
                DELTA_Y.fetch_add(ady, Ordering::Relaxed);
            }

            s.process_buttons(new_buttons, tick);
        }
        _ => {
            PS2_PACKET_IDX.store(0, Ordering::Relaxed);
        }
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Initialize the USB mouse driver.
pub fn init() {
    let mut s = STATE.lock();
    s.x = s.width / 2;
    s.y = s.height / 2;
    INITIALIZED.store(true, Ordering::SeqCst);
    crate::serial_println!("[usb_mouse] USB HID mouse driver initialized");
}

/// Poll for the next pending mouse event.
pub fn poll() -> Option<MouseEvent> {
    let mut s = STATE.lock();
    s.pop_event().map(compact_to_event)
}

/// Return the current absolute cursor position.
pub fn get_position() -> (i32, i32) {
    let s = STATE.lock();
    (s.x, s.y)
}

/// Set screen bounds for cursor clamping.
pub fn set_bounds(w: i32, h: i32) {
    let mut s = STATE.lock();
    s.width = if w > 0 { w } else { 640 };
    s.height = if h > 0 { h } else { 480 };
    s.clamp_position();
}

/// Set acceleration factor (10 = 1.0x, 15 = 1.5x, 20 = 2.0x, etc.).
pub fn set_acceleration(factor: i32) {
    let mut s = STATE.lock();
    s.accel_num = if factor < 1 { 1 } else if factor > 50 { 50 } else { factor };
}

/// Return human-readable mouse driver information.
pub fn mouse_info() -> String {
    let s = STATE.lock();
    let usb = USB_PRESENT.load(Ordering::Relaxed);
    format!(
        "USB Mouse Driver\n\
         Mode:         {}\n\
         Position:     ({}, {})\n\
         Screen:       {}x{}\n\
         Acceleration: {}.{}x\n\
         Buttons:      L={} R={} M={} B4={} B5={}\n\
         Initialized:  {}",
        if usb { "USB HID" } else { "PS/2 fallback" },
        s.x, s.y,
        s.width, s.height,
        s.accel_num / 10, s.accel_num % 10,
        s.buttons[0], s.buttons[1], s.buttons[2],
        s.buttons[3], s.buttons[4],
        INITIALIZED.load(Ordering::Relaxed),
    )
}

/// Return mouse statistics.
pub fn mouse_stats() -> String {
    let s = STATE.lock();
    format!(
        "Mouse Statistics\n\
         Packets:       {}\n\
         Move events:   {}\n\
         Button events: {}\n\
         Scroll events: {}\n\
         Double-clicks: {}\n\
         Queue pending: {}",
        s.packets,
        s.moves,
        s.button_events,
        s.scroll_events,
        s.double_clicks,
        if s.event_head >= s.event_tail {
            s.event_head - s.event_tail
        } else {
            EVENT_BUF_SIZE - s.event_tail + s.event_head
        },
    )
}
